# Generated by Django 4.2.3 on 2023-07-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-03-08'),
            preserve_default=False,
        ),
    ]
